import { GoogleGenerativeAI } from '@google/generative-ai'
import { normalizeSlugTokens, maAdvisorDateFallbackSlug, polishAutoGeneratedSlugVariableSegment } from '@/lib/slugNormalize'
import { loadIntroHistory, saveIntroEntry, extractFirstSentence, buildUsedIntrosBlock } from '@/lib/introHistory'

/** 429/クォータ超過時に順に試すモデル（モデルごとに別枠のことがある） */
const GEMINI_MODELS = ['gemini-2.5-flash'] as const

/** SDK / Google 側のエラーをログ・ユーザー向け詳細用に1行にまとめる */
function formatGeminiCaughtError(e: unknown): string {
  if (e instanceof Error) {
    const withCause = e as Error & { cause?: unknown }
    const tail =
      withCause.cause !== undefined && withCause.cause !== null
        ? ` | cause: ${formatGeminiCaughtError(withCause.cause)}`
        : ''
    return `${e.message}${tail}`
  }
  if (e && typeof e === 'object' && 'message' in e && typeof (e as { message: unknown }).message === 'string') {
    return (e as { message: string }).message
  }
  try {
    return JSON.stringify(e)
  } catch {
    return String(e)
  }
}

function sleep(ms: number): Promise<void> {
  return new Promise(resolve => setTimeout(resolve, ms))
}

/** Google 429 応答の「Please retry in 24.9s」や RetryInfo から待機秒を読む */
function parseRetryDelaySeconds(detail: string): number | null {
  const m1 = detail.match(/Please retry in ([\d.]+)\s*s/i)
  if (m1) {
    const sec = parseFloat(m1[1]!)
    if (Number.isFinite(sec) && sec >= 0) return Math.min(sec, 120)
  }
  const m2 = detail.match(/"retryDelay"\s*:\s*"(\d+)s"/i)
  if (m2) {
    const sec = parseInt(m2[1]!, 10)
    if (Number.isFinite(sec) && sec >= 0) return Math.min(sec, 120)
  }
  return null
}

/**
 * 指定プロンプトで generateContent を実行する。
 * 429（クォータ・分間トークン上限）時は API が示す秒数だけ待って同一モデルを再試行し、
 * それでもダメなら次モデルへ（現状は1モデルのみ）。
 */
async function generateContentWithFallback(apiKey: string, prompt: string): Promise<string> {
  const genAI = new GoogleGenerativeAI(apiKey)
  /** 初回 + 待機後1回のみ（待機25秒×多回は Vercel の関数時間制限に抵触しやすい） */
  const maxQuotaRetriesPerModel = 2
  let lastError: Error | null = null
  let lastDetail = ''

  for (const modelId of GEMINI_MODELS) {
    for (let attempt = 0; attempt < maxQuotaRetriesPerModel; attempt++) {
      try {
        const model = genAI.getGenerativeModel({ model: modelId })
        const result = await model.generateContent(prompt)
        return result.response.text()
      } catch (e) {
        lastError = e instanceof Error ? e : new Error(String(e))
        lastDetail = formatGeminiCaughtError(e)
        console.error(`[Gemini] model=${modelId} attempt=${attempt + 1}/${maxQuotaRetriesPerModel} 失敗:`, lastDetail)
        const msg = lastError.message
        const isQuota = /429|quota|Too Many Requests|Resource exhausted|RESOURCE_EXHAUSTED/i.test(msg) ||
          /429|quota|Resource exhausted|RESOURCE_EXHAUSTED/i.test(lastDetail)
        if (!isQuota) throw lastError

        const waitSec = parseRetryDelaySeconds(lastDetail)
        const canRetry = attempt < maxQuotaRetriesPerModel - 1
        if (canRetry && waitSec != null) {
          const ms = Math.ceil(waitSec * 1000) + 800
          console.warn(`[Gemini] クォータ緩和のため ${ms}ms 待機して再試行します (${modelId})`)
          await sleep(ms)
          continue
        }
        break
      }
    }
  }

  const suffix = lastDetail ? ` [詳細: ${lastDetail}]` : ''
  console.error('[Gemini] クォータ扱いで全モデル失敗', { models: [...GEMINI_MODELS], lastDetail })
  throw new Error(
    'Gemini API の利用上限（無料枠は「1分あたりの入力トークン」など）に達しています。' +
      'しばらく待つか、参照資料（S3）を減らすか、Google AI Studio で課金を有効にしてください。' +
      suffix
  )
}

const TITLE_MARKER = '<<<TITLE>>>'
const BODY_MARKER = '<<<BODY>>>'

const SUPERVISOR_BLOCK = ''

const FOOTER = `導入事例はこちらから
https://www.rice-cloud.info/casestudy/`

export interface RefinedArticle {
  refinedTitle: string
  refinedContent: string
}

export interface FirstDraftResult {
  title: string
  content: string
}

/** 一次執筆・推敲本文から不要なメタテキストを除去する */
function stripSupervisorText(content: string): string {
  if (!content) return content
  return content
    .replace(/\n{3,}/g, '\n\n')
    .trim()
}

/** PREPラベル（P/R/E/P）を本文先頭ラベルから除去する（表示崩れ防止の安全策） */
function stripPrepLabels(content: string): string {
  if (!content) return content
  return content
    .replace(
      /^\s*(?:・\s*)?(?:\*\*)?\s*[PRE]\s*[（(][^）)]+[）)]\s*[：:]\s*/gm,
      ''
    )
    .replace(
      /^\s*(?:・\s*)?(?:\*\*)?\s*P\s*[（(]\s*まとめ\s*[）)]\s*[：:]\s*/gm,
      ''
    )
}

/** 画像バナー配置のプレースホルダー指示を除去する */
function stripBannerPlaceholders(content: string): string {
  if (!content) return content
  return content.replace(/\[ここに[^\]]*画像バナーを配置\]/g, '').replace(/\n{3,}/g, '\n\n')
}

function stripMetaSections(content: string): string {
  if (!content) return content
  const patterns = [
    /\n*関連KW[：:][\s\S]*$/,
    /\n*ロングテール[：:][\s\S]*$/,
    /\n*LLMO対策で意識したポイント[\s\S]*$/,
    /\n*SEO対策で意識したポイント[\s\S]*$/,
    /\n*AIO対策で意識したポイント[\s\S]*$/,
  ]
  let result = content
  for (const pat of patterns) {
    result = result.replace(pat, '')
  }
  return result.trimEnd()
}

/** プロンプトと参照データから一次執筆（タイトル＋本文）を生成する */
export async function generateFirstDraftFromPrompt(
  userPrompt: string,
  targetKeyword?: string,
  dataContext?: string
): Promise<FirstDraftResult> {
  const apiKey = process.env.GEMINI_API_KEY
  if (!apiKey) throw new Error('GEMINI_API_KEY が設定されていません')

  const introHistory = await loadIntroHistory()
  const usedIntrosBlock = buildUsedIntrosBlock(introHistory)

  const prompt = `あなたはM&Aロイヤルアドバイザリー株式会社専属のM&A・事業承継コンテンツストラテジストです。
以下の【参照資料】を徹底的に読み込み、M&Aロイヤルアドバイザリーにしか書けない記事を執筆してください。

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【M&Aロイヤルアドバイザリー 固定情報】
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
・会社名：M&Aロイヤルアドバイザリー株式会社
・事業：M&A仲介・事業承継支援（完全成功報酬型）
・強み：着手金・中間金ゼロの完全成功報酬、オーナーに寄り添う地域密着型M&A支援、M&Aが最善の選択である場合のみ提案する誠実なアドバイザリー
・サービス：譲渡・売却サービス / 譲受・買収サービス / 株価算定サービス
・お問い合わせ：https://ma-la.co.jp/inquiry/
・導入事例：https://ma-la.co.jp/result/
・「[ここに〜画像バナーを配置]」のようなプレースホルダー指示は絶対に出力しないこと。画像バナーの配置はシステム側で自動処理される。

■ 個人情報・機密情報の保護（最重要・違反厳禁）
・本文中に**実在の企業名（M&Aロイヤルアドバイザリー株式会社を除く）・個人名・住所・電話番号**を絶対に出力しないこと。
・参照資料に社名・個人名が含まれていても、記事本文では必ず「A社（製造業・年商約10億円）」「ある建設会社」のように匿名化して言及すること。
・業種・年商規模・従業員数などは、特定企業を推定できない範囲でのみ使用可。
・M&A事例を引用する場合は「M&Aロイヤルアドバイザリーが支援したあるケースでは〜」という形式にし、固有名詞は一切使わないこと。

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【出力形式】※必ずこの形式を守ること
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
タイトル：（記事タイトル）
---
（本文）

※「---」の下には記事本文のみを記述してください。

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【執筆テーマ・指示】
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${userPrompt}

${targetKeyword?.trim() ? `ターゲットキーワード：${targetKeyword}\n※タイトルと本文の自然な箇所に必ず盛り込むこと。` : ''}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【参照資料】
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${dataContext?.trim() ? `
以下の資料を読み込んだ上で、下記の【資料活用ルール】に従って執筆すること。

${dataContext}
` : '（資料なし：プロンプトのみで執筆）'}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【資料活用ルール】※資料がある場合は必ず全て実行すること
━━━━━━━━━━━━━━━━━━━━━━━━━━━━

■ 参照資料と【執筆テーマ・指示】の優先順位（最重要）
1. 【執筆テーマ・指示】およびターゲットキーワードが、記事の主題・見出し構成・論点の最優先。参照資料は補助であり、資料の目次に従って記事を書いてはならない。
2. 参照資料に「ERPの定義」「導入ステップ」「よくある手順」などの**定番・網羅的な解説フロー**が含まれていても、それを**記事の章立てとしてなぞらない**。今回のテーマ・KWに**直接必要な事実・数値・用語・事例だけ**を抜き出して使う。
3. テーマとズレた一般論を「資料にあるから」という理由で厚く書かない。不要なセクションは設けない。
4. 「S3資料にも記載されているように」「資料によると」「社内資料では」など、**参照資料そのものを指し示すメタな言い回しは禁止**。読者向けの自然な本文に溶け込ませる。
5. 資料の断片が毎回似ていても、**今回のプロンプトで指定した切り口・論点だけ**を深掘りし、別記事と同じ見出し並びの汎用解説にしない。

■ Ahrefsデータがある場合の使い方
1. 競合記事が上位表示されているキーワードと検索意図を把握する
2. 競合記事が薄い・触れていない論点を特定する
3. その論点をM&Aロイヤルアドバイザリー記事の差別化ポイントとして見出しに使う
4. 競合より詳しく・具体的に書く（文字数・事例数・具体性で上回る）
5. 競合が使っていない切り口・角度から題材にアプローチする

■ M&Aロイヤルアドバイザリー社内資料（事例・案件記録・ノウハウ等）がある場合の使い方
1. 資料中の具体的な数値・金額・期間・業種を、**今回のテーマに関係するときだけ**本文に使う（無関係な定番統計の羅列は避ける）
2. 「〜というケースがありました」という形で実際のM&A事例を本文に組み込む（テーマと結びつく事例に限定）
3. 「M&Aロイヤルアドバイザリーでは〜」「現場のアドバイザリー経験から感じるのは〜」という一人称の知見として書く
4. 一般論を述べた後、必ずM&Aロイヤルアドバイザリーの現場視点でその一般論を補強または修正する（ただし上記「参照資料の優先順位」に反しないこと）
5. 資料にある数値は出典明記不要でそのまま使用してよい

■ 両方ある場合
Ahrefsで競合の弱点を特定 → M&Aロイヤルアドバイザリー社内資料でその弱点を埋める
という構造で記事全体を設計する

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【執筆の絶対ルール】
━━━━━━━━━━━━━━━━━━━━━━━━━━━━

❶ 導入（冒頭の2〜3文）の設計
■ あなたの仕事：
今回の記事テーマ・キーワード・想定読者（中堅〜大企業の経営企画・IT部門・DX推進担当者）を踏まえ、
「この記事でしか使えない、この記事だからこそ意味がある一文目」を自分で考えること。
他の記事の冒頭をコピーしたような汎用的な書き出しは一切禁止。

■ 導入で禁止すること（以下に該当する書き出しは不可）：
・「近年〜」「〜が問題となっています」「〜が注目されています」などの時事導入
・「少子高齢化が進む中〜」「後継者不足が深刻化する中〜」のような定型社会問題導入
・「M&Aとは〜」「事業承継とは〜」から始まる辞書的な定義導入
・「ある日突然〜」「ふと気がつくと〜」のような物語調の紋切り型
・「〜という言葉を耳にする機会が増えました」のような受動的な時事導入
・前回までの記事と同じ構造・同じ語彙の導入（下記の使用禁止リスト参照）

■ 導入で意識すること：
・読者（会社売却・M&Aを検討しているオーナー経営者）が「お、これは今まで読んだ記事と違うな」と感じる一文目にする
・テーマに固有の具体的な場面・数字・問い・事実から入る
・「悩みの共感」以外にも、反直感的な事実提示、具体的なシーン描写、
  読者への直接的な問いかけ、業界の構造的な変化の指摘、
  意外な統計データ、現場で実際に聞いた一言の引用など、自由にアプローチしてよい
・同じメディアの他記事と並んだときに「毎回違う切り口で書いている」と感じられることが最重要

${usedIntrosBlock}

❷ M&Aロイヤルアドバイザリーの実績・視点を本文の根拠として使う
「完全成功報酬での成約実績」「地域密着型M&A支援の事例」「オーナーに寄り添ったアドバイザリー経験」等を
抽象的な説明の裏付けとして本文中で活用すること。
「M&Aロイヤルアドバイザリーでは〜」という形で必ず2〜3箇所登場させること。

❸ 一般論で終わらせない
各見出しセクションで「一般的には〜」で終わる説明の後に、
必ず「M&Aロイヤルアドバイザリーの現場では〜」「実際のM&Aアドバイザリーの経験では〜」という
具体・固有の情報を続けること。

❹ PREP法で各セクションを構成する
P（結論）→ R（理由）→ E（M&Aロイヤルアドバイザリー事例・具体例）→ P（まとめ）
の順で書くこと。特にE（事例）を省略しないこと。
ただし本文中に「P（結論）」「R（理由）」「E（M&Aロイヤルアドバイザリー事例・具体例）」「P（まとめ）」などのラベルは出力しないこと。

❺ 末尾は必ずCTAで締める
- まとめセクションの末尾には必ず以下の文章をそのまま使うこと（一字一句変更しないこと）：
「M&Aロイヤルアドバイザリーは、着手金・中間金ゼロの完全成功報酬型でM&A・事業承継を支援しています。M&Aが最善の選択である場合のみご提案しますので、まずはお気軽にご相談ください。」
- その後に「M&A成約実績はこちらから https://ma-la.co.jp/result/」を必ず含めること。
- さらにその下に「無料相談のお問い合わせはこちら https://ma-la.co.jp/inquiry/」を必ず含めること。

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【構成・文体ルール】
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
- 本文は2500文字以上（資料が豊富な場合は3000文字以上を目指す）
- 見出しは「1. 」「2. 」番号付き形式、小見出しは「1-1.」形式
- 専門用語には初出時に括弧で解説（例：M&A（Mergers and Acquisitions：企業の合併・買収）、事業承継（後継者への経営権の移譲）等）
- マークダウン記法（##・**等）は使用しない
- 箇条書きは多用しない。文章で表現できるものは文章にする
- 文末表現のバリエーションを意識する（〜です・〜ますの繰り返しを避ける）
- 対象読者：会社売却・事業承継・M&Aを検討している中小企業オーナー・経営者（M&A未経験者にも分かりやすく）

- 記事の末尾に「よくある質問（FAQ）」セクションを含めること。Q. と A. の形式で5つ程度の質問と回答を作成すること。質問はターゲットキーワードに関連するユーザーの疑問を反映したものにすること。`.trim()

  const raw = await generateContentWithFallback(apiKey, prompt)

  let text = raw
    .replace(/\*\*(.+?)\*\*/g, '$1')
    .replace(/\*(.*?)\*/g, '$1')
    .replace(/^\s*\*\s+/gm, '・ ')
    .replace(/\*/g, '')
    .replace(/^#{1,6}\s+/gm, '')

  const titleMatch = text.match(/タイトル：(.+)/)
  const separatorIndex = text.indexOf('---')

  if (!titleMatch && separatorIndex === -1) {
    throw new Error('生成結果の形式が不正です。再度お試しください。')
  }

  const title = titleMatch?.[1]?.trim() || '（タイトルなし）'
  let content = separatorIndex >= 0
    ? text.slice(separatorIndex + 3).trim().replace(/^-\s*/, '')
    : text.replace(/タイトル：.+/, '').trim()

  // 本文の先頭にタイトルが残っていれば削除
  content = content.replace(/^タイトル：[^\n]+\n+/, '').trim()
  if (title !== '（タイトルなし）' && content.startsWith(title)) {
    content = content.substring(title.length).trim()
  }
  content = stripPrepLabels(content)
  content = stripBannerPlaceholders(content)
  content = stripMetaSections(content)

  try {
    const firstSentence = extractFirstSentence(content)
    if (firstSentence) {
      await saveIntroEntry(targetKeyword ?? '', firstSentence)
    }
  } catch (e) {
    console.warn('[IntroHistory] 保存失敗（記事生成には影響なし）:', e)
  }

  return {
    title: title || '（タイトルなし）',
    content: content || '',
  }
}

export async function refineArticleWithGemini(
  title: string,
  content: string,
  targetKeyword?: string
): Promise<RefinedArticle> {
  // 元記事から監修者テキストを事前に除去
  const cleanedContent = stripSupervisorText(content)

  const apiKey = process.env.GEMINI_API_KEY
  if (!apiKey) throw new Error('GEMINI_API_KEY が設定されていません')

  const prompt = `あなたはM&Aロイヤルアドバイザリー株式会社の編集長です。
以下の記事を精査・推敲してください。

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【M&Aロイヤルアドバイザリー 固定情報：推敲後も必ず維持すること】
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
・末尾CTA：M&A成約実績はこちらから https://ma-la.co.jp/result/
  無料相談のお問い合わせはこちら https://ma-la.co.jp/inquiry/

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【元記事】
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
タイトル：${title}

本文：
${cleanedContent}

${targetKeyword?.trim() ? `ターゲットキーワード：${targetKeyword}` : ''}

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【推敲チェックリスト：上から順に確認・修正すること】
━━━━━━━━━━━━━━━━━━━━━━━━━━━━

【A. タイトル】
□ ターゲットキーワードが自然に含まれているか
□ 数字・具体性が入っているか（「5つの」「失敗しない」等）
□ 32文字以内か
□ クリックしたくなる表現になっているか

【B. 冒頭】
□ 以下の定型フレーズで始まっていないか確認する：
  ・「近年〜」「〜が問題となっています」「〜が注目されています」
  ・「少子高齢化が進む中〜」「後継者不足が深刻化する中〜」のような定型社会問題導入
  ・「M&Aとは〜」「事業承継とは〜」から始まる辞書的な定義
  ・「ある日突然〜」「ふと気がつくと〜」
  ・「〜という言葉を耳にする機会が増えました」
  → 該当していたら、この記事のテーマに固有の具体的な場面・事実・問いから始まる導入に書き直す
□ 会社売却・事業承継・M&Aを検討しているオーナー経営者が「これは今まで読んだ記事と違う切り口だ」と感じる導入になっているか
  → 汎用的な悩み描写の繰り返しになっていたら、テーマ固有の具体性を入れて書き直す

【C. M&Aロイヤルアドバイザリーのオリジナリティ強化】
□ 「一般論」で終わっている箇所を見つけ、M&Aロイヤルアドバイザリーの実務知見に基づく具体的な示唆に書き換えること
  → 例：「M&Aの価格交渉は重要です」のような文は、M&Aロイヤルアドバイザリーの現場経験を反映した具体表現に変える
  → ただし、元記事や資料に根拠がない事実は捏造しないこと。裏付けのない具体例（「○○を基準にして」等のプレースホルダー的表現）は絶対に出力しない
□ 現場感のある表現を自然に追加すること
  → 「よく見るのは〜」「実際にあったケースでは〜」「現場でよく聞くのは〜」など、実務者の語り口を織り交ぜる
□ 引用形式で1〜2文、意思決定の言葉や現場の表現を入れること
  → 例：「"オーナーが本当に求めているのは、高い売却価格より、会社と従業員の未来"——これはM&Aロイヤルアドバイザリーが繰り返し経験してきた教訓です」
□ 「M&Aロイヤルアドバイザリーでは〜」という固有の視点・事例が2〜3箇所あるか → なければ追加する
□ M&Aロイヤルアドバイザリーの実績（完全成功報酬での成約・地域密着型支援・オーナーに寄り添う提案）が本文中で自然に使われているか → なければ適切な箇所に挿入する

【D. AIO / LLMO 構造最適化】
□ 記事冒頭に「結論サマリー」（2〜3文）があるか確認し、なければ追加すること
  → 検索エンジンやLLMが記事の核心を素早く把握できるようにする
□ 各H2セクションの冒頭にも1文の結論を配置すること（逆ピラミッド構造）
  → そのセクションで何が分かるかを最初に伝え、詳細をその後に展開する
□ 「〜とは？」「〜のメリットは？」のような質問形式の見出しがあれば、直後に端的な回答を1文で配置すること
□ 箇条書きと表を適切に使い、LLMが引用しやすい構造にすること
  → 3つ以上の並列情報は箇条書き化を検討する

【D2. SEO + 読みやすさの改善】
□ ターゲットキーワードが自然に含まれているか確認し、不足なら見出しや本文に追加すること
  → キーワードの不自然な詰め込みはしない。あくまで自然な文脈で使う
□ 接続詞の重複（「また」「そして」「さらに」の連続）を修正すること
  → 同じ接続詞が3文以内に2回以上出ていたら別の表現に言い換える
□ 専門用語は初出時に括弧書きで補足がされているか確認すること
  → 例：ERP（Enterprise Resource Planning：統合基幹業務システム）
□ 読者が「次に何をすべきか」が分かるCTAまたはまとめを末尾に配置すること
□ 文末表現のバリエーションを増やす（〜です・〜ますの連続を避ける）
□ 冗長な表現・繰り返しを削除する

【D3. 構成・フォーマットルール】
□ アスタリスク（*）は一切使用禁止。箇条書きは必ず「・」を使うこと（* で始める箇条書きは不可。出力に * が1つも含まれないようにすること）
□ PREPで整理する際も「P（結論）」「R（理由）」「E（事例）」「P（まとめ）」などのラベル文字は本文に出力しないこと
□ 「[ここに〜画像バナーを配置]」のようなプレースホルダー指示は絶対に出力しないこと。画像バナーの配置はシステム側で自動処理されるため、本文に含めてはならない
□ 「S3資料」「資料に」「社内資料に」「参照資料に」など、資料を直接指すメタ表現があれば削除し、読者向けの自然な表現に直す
□ タイトル・ターゲットキーワードと弱く結びついたまま、M&A/事業承継の汎用教科書型（例：M&Aの定義→手続き一覧→定番のまとめだけ）に偏っていないか。偏っている場合は、タイトルとKWが約束した論点に沿って見出しと本文を組み替え、無関係な網羅セクションは削る・圧縮する（末尾の固定CTA・実績の扱いなど既存ルールは維持）

【D4. 個人情報・機密情報の保護（違反厳禁）】
□ 本文に実在の企業名（M&Aロイヤルアドバイザリー株式会社を除く）が含まれていないか → あれば「A社（業種・規模）」等に匿名化する
□ 個人名・住所・電話番号が含まれていないか → あれば削除する
□ M&A事例の引用が「M&Aロイヤルアドバイザリーが支援したあるケースでは〜」のように匿名化されているか

【E. 末尾CTA】
□ M&Aロイヤルアドバイザリーへの相談を促す自然な文章があるか
□ 「M&A成約実績はこちらから https://ma-la.co.jp/result/」で締めているか
  → なければ追加する
□ その下に「無料相談のお問い合わせはこちら https://ma-la.co.jp/inquiry/」を追加しているか
  → なければ追加する

━━━━━━━━━━━━━━━━━━━━━━━━━━━━
【出力形式】※必ずこの形式を守ること
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
タイトル：（推敲後タイトル）
---
（推敲後本文）

※「---」の下には推敲後本文のみを記述してください。`.trim()

  let text = await generateContentWithFallback(apiKey, prompt)
  text = text
    .replace(/\*\*(.+?)\*\*/g, '$1')
    .replace(/\*(.*?)\*/g, '$1')
    .replace(/^\s*\*\s+/gm, '・ ')
    .replace(/\*\s+/g, '・ ')
    .replace(/\*/g, '')
    .replace(/^#{1,6}\s+/gm, '')

  const titleMatch = text.match(/タイトル：(.+)/)
  const separatorIndex = text.indexOf('---')

  if (!titleMatch && separatorIndex === -1) {
    throw new Error('推敲結果の形式が不正です。再度お試しください。')
  }

  const refinedTitle = titleMatch?.[1]?.trim() || title
  let refinedContent = separatorIndex >= 0
    ? text.slice(separatorIndex + 3).trim().replace(/^-\s*/, '')
    : text.replace(/タイトル：.+/, '').trim()

  // 本文の先頭にタイトルが残っていれば削除
  refinedContent = refinedContent.replace(/^タイトル：[^\n]+\n+/, '').trim()
  if (refinedTitle && refinedContent.startsWith(refinedTitle)) {
    refinedContent = refinedContent.substring(refinedTitle.length).trim()
  }

  refinedContent = stripSupervisorText(refinedContent)
  refinedContent = stripPrepLabels(refinedContent)
  refinedContent = stripBannerPlaceholders(refinedContent)
  refinedContent = stripMetaSections(refinedContent)

  return {
    refinedTitle: refinedTitle || title,
    refinedContent: refinedContent || content,
  }
}

const SLUG_PREFIX = 'ma-loyal-'

function sanitizeSlugSegment(raw: string): string {
  return normalizeSlugTokens(
    raw
      .trim()
      .toLowerCase()
      .replace(/[^a-z0-9\s-]/g, '')
      .replace(/\s+/g, '-')
      .replace(/-+/g, '-')
      .replace(/^-|-$/g, '')
      .slice(0, 60)
  )
}

/** 記事タイトル・本文・キーワードから SEO 向け英語スラッグを生成する（先頭は常に erp-saas- 固定、続きは本文内容に即した固有部分） */
export async function generateSlugFromGemini(
  title: string,
  targetKeyword?: string,
  articleBody?: string
): Promise<string> {
  const apiKey = process.env.GEMINI_API_KEY
  if (!apiKey?.trim()) return fallbackSlug()

  const kwPart = targetKeyword?.trim() ? `\nTarget keyword: ${targetKeyword.trim()}` : ''
  const bodyExcerpt = (articleBody ?? '').trim().slice(0, 2000)
  const bodyPart = bodyExcerpt
    ? `\nArticle body (Japanese excerpt — use this to capture the specific topic and wording):\n${bodyExcerpt}`
    : ''

  const prompt = `You are an SEO specialist. The URL slug MUST start with the fixed prefix "ma-loyal-" followed by a UNIQUE English segment for this article.

You will output ONLY the variable segment: the part that comes AFTER "ma-loyal-". Do NOT include "ma-loyal" or "ma-loyal-" in your output.

CRITICAL: Respond in English only. NEVER use Japanese characters. Output ONLY that segment, nothing else.

RULES for the variable segment (after the fixed prefix):
- Use ONLY lowercase English letters (a-z), numbers (0-9), and hyphens (-)
- 3 to 5 words separated by hyphens
- Reflect the SPECIFIC topic using BOTH the title AND the article body excerpt below (body is primary for uniqueness)
- Do NOT use Japanese, Chinese, or any non-ASCII characters
- Do NOT output a standalone "ma" or "merger" token in the variable segment. The fixed prefix "ma-loyal-" already implies M&A context; use concrete topic terms (e.g. succession, acquisition, valuation, sell, transfer) instead of repeating "ma"
- Prefer full words such as "succession" over abbreviations when valid within the word budget

EXAMPLES (output = variable segment only):
- Title/body about M&A business succession → business-succession-guide
- Title/body about company sale procedure → company-sale-steps
- Title/body about M&A costs and fees → ma-cost-fee-structure
- Title/body about stock valuation → stock-valuation-basics
- Title/body about finding M&A buyer → buyer-matching-process

Title: ${title.trim()}${kwPart}${bodyPart}

Variable segment after "ma-loyal-":`

  try {
    const raw = await generateContentWithFallback(apiKey, prompt)
    let segment = sanitizeSlugSegment(raw)
    if (segment.startsWith('ma-loyal-')) {
      segment = segment.slice('ma-loyal-'.length).replace(/^-+/, '')
    }
    segment = segment.replace(/^ma-loyal-?/, '').replace(/^-+/, '')
    segment = polishAutoGeneratedSlugVariableSegment(segment)
    const full = segment.length >= 3 ? `${SLUG_PREFIX}${segment}` : fallbackSlug()
    return normalizeSlugTokens(full)
  } catch (e) {
    console.warn('Gemini slug generation failed:', (e as Error)?.message)
    return fallbackSlug()
  }
}

function fallbackSlug(): string {
  return maAdvisorDateFallbackSlug()
}

/** 記事タイトル・本文から画像生成用の英文プロンプトを1文で生成する（Stable Diffusion用） */
export async function generateImagePromptFromArticle(
  title: string,
  content: string
): Promise<string> {
  const apiKey = process.env.GEMINI_API_KEY
  if (!apiKey?.trim()) throw new Error('GEMINI_API_KEY が設定されていません')

  const contentSnippet = content.trim().slice(0, 1800)
  const prompt = `You are an expert at writing image generation prompts for professional Japanese business article thumbnails. Style: Adobe Stock–like corporate / M&A / business succession / investment banking imagery — sophisticated, trustworthy, premium feel, varied compositions.

Given the TITLE and CONTENT (Japanese) below, output exactly ONE English sentence for a photorealistic 16:9 horizontal stock photo.

STEP 1 — Pick EXACTLY ONE archetype at random (use genuine randomness; do not default to the first). Match the article mood when obvious, but still vary across requests.

ARCHETYPES:
1) Overhead flat-lay: dark wooden desk, business contract documents, fountain pen, wine-red accent folder, no people.
2) Overhead flat-lay: M&A due diligence documents, financial printouts, reading glasses, premium pen, minimal dark desk, no people.
3) Overhead: abstract financial data printouts and graphs, tablet showing abstract valuation dashboard, pen, clean desk, no people, no readable numbers.
4) Dark premium desk workspace: open laptop with abstract business analytics, scattered confidential document folders, shallow depth of field, no people.
5) Two business professionals in formal suits at premium conference desk, hands pointing at contract documents, faces soft blur or cropped, no camera-facing portrait.
6) Side angle premium business meeting: executives over documents and tablets, emphasis on handshake or contract signing, faces not dominant, sophisticated modern office.
7) Abstract financial visualization: stock market abstract chart overlay, dark blue and gold tones, corporate investment feel, no people.
8) Premium collaboration: dark mahogany desk, hands gesturing mid-negotiation, contract documents and smartphone, strong bokeh background, formal business attire, second person blurred.
9) Executive conference room wide shot: team from behind or silhouettes, large screen showing abstract M&A transaction diagram, no clear facial close-ups.
10) Business handshake mood: two hands shaking in front of abstract blurred city or office background, formal attire cuffs visible, warm gold and deep tone palette, no readable text.
11) Abstract corporate merger: two puzzle pieces or abstract geometric shapes connecting, clean minimalist style, dark wine-red and gold accent colors, no people.
12) Default corporate: clean premium Japanese office desk with documents and laptop, abstract business analytics screen, deep wine-red (#9b0000) / gold / white palette, no people.

GLOBAL RULES (mandatory):
- Never ask for letters, numbers, logos, watermarks, subtitles, or readable text. Charts and screens must be abstract / illegible only.
- People allowed ONLY in archetypes 5–6, 8–10. Then: no selfie, no glamor portrait; hands and materials in focus; faces partial or softly blurred.
- Photorealistic, professional lighting, premium palette of deep wine-red (#9b0000), gold (#97876A), white, charcoal grey.

OUTPUT: One English sentence only, max 45 words, no quotation marks, no explanation.

TITLE:
${title.trim()}

CONTENT (excerpt):
${contentSnippet}

Your single English sentence:`

  const raw = await generateContentWithFallback(apiKey, prompt)
  const sentence = raw.trim().replace(/^["']|["']$/g, '').trim()
  return (
    sentence ||
    'overhead flat-lay of M&A business contract documents and fountain pen on dark premium desk, photorealistic corporate stock photo, deep wine-red and gold palette, 16:9'
  )
}
