const SLUG_PREFIX = 'erp-saas-'

/**
 * 推敲APIなどが返す「erp-saas-」以降の可変部分だけを読みやすくする。
 * 新規自動生成向け。ユーザーがカスタム入力したスラッグには適用しないこと。
 *
 * - トークン sme → small-business（略称の意味が伝わりにくいため）
 * - 単独トークン erp/saas を除去（先頭固定 erp-saas と意味が重複しやすいため）
 */
export function polishAutoGeneratedSlugVariableSegment(segment: string): string {
  let s = segment
    .trim()
    .toLowerCase()
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '')
  if (!s) return s
  s = normalizeSlugTokens(s)
  s = s.replace(/(^|-)sme(?=-|$)/g, '$1small-business')
  let prev: string
  do {
    prev = s
    s = s.replace(/(^|-)(?:erp|saas)(?=-|$)/g, '$1').replace(/-+/g, '-').replace(/^-|-$/g, '')
  } while (s !== prev)
  return s
}

/**
 * スラッグ内の誤分割トークンを正規化する。
 * 例: e-r-p → erp, s-a-a-s → saas
 */
export function normalizeSlugTokens(slug: string): string {
  return slug
}

/** Gemini / WordPress 投稿用: API 未取得時・空スラッグ時の日付ベース英語スラッグ */
export function maAdvisorDateFallbackSlug(): string {
  const d = new Date()
  const tail = `article-${d.getFullYear()}${String(d.getMonth() + 1).padStart(2, '0')}${String(d.getDate()).padStart(2, '0')}`
  return `${SLUG_PREFIX}${tail}`
}

/**
 * REST・JSON-LD 用の最終スラッグ（英字・数字・ハイフンのみ、常に erp-saas- で開始）。
 * 空・不正・サフィックス短すぎは日付フォールバック。
 */
export function resolveCanonicalPostSlug(raw: string | undefined | null): string {
  let s = (raw ?? '').trim().toLowerCase()
  s = s.replace(/[^a-z0-9-]/g, '').replace(/-+/g, '-').replace(/^-|-$/g, '')
  if (!s) return maAdvisorDateFallbackSlug()

  if (s.startsWith(SLUG_PREFIX)) {
    // そのまま
  } else if (s.startsWith('erp-saas')) {
    s = SLUG_PREFIX + s.slice('erp-saas'.length).replace(/^-+/, '')
  } else {
    s = SLUG_PREFIX + s.replace(/^-+/, '')
  }
  s = normalizeSlugTokens(s)
  const after = s.startsWith(SLUG_PREFIX) ? s.slice(SLUG_PREFIX.length) : ''
  if (after.length < 3) return maAdvisorDateFallbackSlug()
  return s
}
